workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: always
    - when: never

stages:
  - build

build-job:
  stage: build
  image: maven:3.9.9-eclipse-temurin-21
  script:
    - |
      if [ -f ./mvnw ]; then
        chmod +x ./mvnw
        ./mvnw clean package
      else
        mvn clean package
      fi
  artifacts:
    name: app-jar
    paths:
      - ./target/*.jar